import Foundation
import ProjectDescription
import GekoCore
import GekoGraph
import GekoSupport
import GekoSupportTesting
import XCTest

@testable import GekoLoader

final class WorkspaceGenerationOptionsManifestMapperTests: GekoTestCase {
    func test_from_whenAutomaticXcodeSchemeIsDefault() throws {
        // Given
        let temporaryPath = try temporaryPath()
        let generatorPaths = GeneratorPaths(manifestDirectory: temporaryPath)
        var actual = ProjectDescription.Workspace.GenerationOptions.options(
            enableAutomaticXcodeSchemes: nil,
            autogeneratedWorkspaceSchemes: .disabled,
            lastXcodeUpgradeCheck: .init("1.2.3"),
            renderMarkdownReadme: false
        )

        // When
        try actual.resolvePaths(generatorPaths: generatorPaths)
        try actual.resolveGlobs()

        // Then
        XCTAssertEqual(
            actual,
            .init(
                enableAutomaticXcodeSchemes: nil,
                autogeneratedWorkspaceSchemes: .disabled,
                lastXcodeUpgradeCheck: .init("1.2.3"),
                renderMarkdownReadme: false,
                autogenerateLocalPodsProjects: .disabled,
                autogenerateLocalPodsSchemes: .disabled,
                commonSettings: [],
                configurations: ["Debug": .debug, "Release": .release]
            )
        )
    }

    func test_from_whenAutomaticXcodeSchemeIsDisabled() throws {
        // Given
        let temporaryPath = try temporaryPath()
        let generatorPaths = GeneratorPaths(manifestDirectory: temporaryPath)
        var actual = ProjectDescription.Workspace.GenerationOptions.options(
            enableAutomaticXcodeSchemes: false,
            autogeneratedWorkspaceSchemes: .disabled
        )

        // When
        try actual.resolvePaths(generatorPaths: generatorPaths)
        try actual.resolveGlobs()

        // Then
        XCTAssertEqual(
            actual,
            .init(
                enableAutomaticXcodeSchemes: false,
                autogeneratedWorkspaceSchemes: .disabled,
                lastXcodeUpgradeCheck: nil,
                renderMarkdownReadme: false,
                autogenerateLocalPodsProjects: .disabled,
                autogenerateLocalPodsSchemes: .disabled,
                commonSettings: [],
                configurations: ["Debug": .debug, "Release": .release]
            )
        )
    }

    func test_from_whenAutomaticXcodeSchemeIsEnabled() throws {
        // Given
        let temporaryPath = try temporaryPath()
        let generatorPaths = GeneratorPaths(manifestDirectory: temporaryPath)
        var actual = ProjectDescription.Workspace.GenerationOptions.options(
            enableAutomaticXcodeSchemes: true,
            autogeneratedWorkspaceSchemes: .disabled,
            renderMarkdownReadme: false
        )

        // When
        try actual.resolvePaths(generatorPaths: generatorPaths)
        try actual.resolveGlobs()

        // Then
        XCTAssertEqual(
            actual,
            .init(
                enableAutomaticXcodeSchemes: true,
                autogeneratedWorkspaceSchemes: .disabled,
                lastXcodeUpgradeCheck: nil,
                renderMarkdownReadme: false, 
                autogenerateLocalPodsProjects: .disabled,
                autogenerateLocalPodsSchemes: .disabled,
                commonSettings: [],
                configurations: ["Debug": .debug, "Release": .release]
            )
        )
    }

    func test_from_whenAutogenerationOptionsIsEnabled() throws {
        // Given
        let temporaryPath = try temporaryPath()
        let generatorPaths = GeneratorPaths(manifestDirectory: temporaryPath)
        var actual = ProjectDescription.Workspace.GenerationOptions.options(
            enableAutomaticXcodeSchemes: true,
            autogeneratedWorkspaceSchemes: .enabled(
                codeCoverageMode: .all,
                testingOptions: [.parallelizable, .randomExecutionOrdering]
            )
        )

        // When
        try actual.resolvePaths(generatorPaths: generatorPaths)
        try actual.resolveGlobs()

        // Then
        XCTAssertEqual(
            actual,
            .init(
                enableAutomaticXcodeSchemes: true,
                autogeneratedWorkspaceSchemes: .enabled(
                    codeCoverageMode: .all,
                    testingOptions: [.parallelizable, .randomExecutionOrdering]
                ),
                lastXcodeUpgradeCheck: nil,
                renderMarkdownReadme: false,
                autogenerateLocalPodsProjects: .disabled,
                autogenerateLocalPodsSchemes: .disabled,
                commonSettings: [],
                configurations: ["Debug": .debug, "Release": .release]
            )
        )
    }

    func test_from_whenAutogenerationLocalPodSchemesIsEnabled() throws {
        // Given
        let temporaryPath = try temporaryPath()
        let testPlanPathsMock = try createFiles(["abc.xctestplan"])
        let generatorPaths = GeneratorPaths(manifestDirectory: temporaryPath)
        var actual = ProjectDescription.Workspace.GenerationOptions.options(
            autogenerateLocalPodsSchemes: .enabled(testPlans: ["*.xctestplan"])
        )

        // When
        try actual.resolvePaths(generatorPaths: generatorPaths)
        try actual.resolveGlobs()

        // Then
        XCTAssertEqual(
            actual,
            .init(
                enableAutomaticXcodeSchemes: false,
                autogeneratedWorkspaceSchemes: .enabled(
                    codeCoverageMode: .disabled,
                    testingOptions: []
                ),
                lastXcodeUpgradeCheck: nil,
                renderMarkdownReadme: false,
                autogenerateLocalPodsProjects: .disabled,
                autogenerateLocalPodsSchemes: .enabled(testPlans: testPlanPathsMock),
                commonSettings: [],
                configurations: ["Release": .release, "Debug": .debug]
            )
        )
    }

    func test_from_whenAutogenerationLocalPodSchemesIsDisabled() throws {
        // Given
        let temporaryPath = try temporaryPath()
        let generatorPaths = GeneratorPaths(manifestDirectory: temporaryPath)
        var actual = ProjectDescription.Workspace.GenerationOptions.options(
            autogenerateLocalPodsSchemes: .disabled
        )

        // When
        try actual.resolvePaths(generatorPaths: generatorPaths)
        try actual.resolveGlobs()

        // Then
        XCTAssertEqual(
            actual,
            .init(
                enableAutomaticXcodeSchemes: false,
                autogeneratedWorkspaceSchemes: .enabled(
                    codeCoverageMode: .disabled,
                    testingOptions: []
                ),
                lastXcodeUpgradeCheck: nil,
                renderMarkdownReadme: false,
                autogenerateLocalPodsProjects: .disabled,
                autogenerateLocalPodsSchemes: .disabled,
                commonSettings: [],
                configurations: ["Release": .release, "Debug": .debug]
            )
        )
    }
}
