import Foundation
import GekoSupportTesting
import GekoGraph
import XCTest
import struct ProjectDescription.AbsolutePath

@testable import GekoLoader

final class CocoapodsProjectOptionsProviderTests: GekoUnitTestCase {

    func testProvideWithoutAutomaticSchemesForLocalPodsGeneration() throws {
        // arrange
        let generationOptionsMock = GekoGraph.Workspace.GenerationOptions(
            enableAutomaticXcodeSchemes: nil,
            autogeneratedWorkspaceSchemes: .disabled,
            lastXcodeUpgradeCheck: nil,
            renderMarkdownReadme: false,
            autogenerateLocalPodsProjects: .disabled,
            autogenerateLocalPodsSchemes: .disabled,
            commonSettings: [],
            configurations: [:]
        )
        let sut = CocoapodsProjectOptionsProvider(workspaceGenerationOptions: generationOptionsMock, testPlansByTarget: [:])

        // act
        let options = sut.provide(for: [Target.test()])

        // assert
        XCTAssertEqual(options.automaticSchemesOptions, .disabled)
        XCTAssertEqual(options.disableBundleAccessors, true)
        XCTAssertEqual(options.disableShowEnvironmentVarsInScriptPhases, false)
        XCTAssertEqual(options.textSettings.indentWidth, nil)
        XCTAssertEqual(options.textSettings.tabWidth, nil)
        XCTAssertEqual(options.textSettings.usesTabs, nil)
        XCTAssertEqual(options.textSettings.wrapsLines, nil)
    }

    func testProvideWithAutomaticSchemesForLocalPodsGeneration() throws {
        // arrange
        let testPlanPathsMock = try createFiles(["a.xctestplan", "b.xctestplan"])
        let generationOptionsMock = GekoGraph.Workspace.GenerationOptions(
            enableAutomaticXcodeSchemes: nil,
            autogeneratedWorkspaceSchemes: .disabled,
            lastXcodeUpgradeCheck: nil,
            renderMarkdownReadme: false,
            autogenerateLocalPodsProjects: .disabled,
            autogenerateLocalPodsSchemes: .enabled(testPlans: testPlanPathsMock),
            commonSettings: [],
            configurations: [:]
        )
        let testPlansByTargetMock: [String: [AbsolutePath]] = [
            "TestTargetA": [testPlanPathsMock[0]],
            "TestTargetB": [testPlanPathsMock[1]]
        ]
        let sut = CocoapodsProjectOptionsProvider(workspaceGenerationOptions: generationOptionsMock, testPlansByTarget: testPlansByTargetMock)

        // act
        let options = sut.provide(for: [Target.test(name: "TestTargetA"), Target.test(name: "TestTargetB")])

        // assert
        XCTAssertEqual(options.automaticSchemesOptions, .enabled(
            targetSchemesGrouping: .pods,
            codeCoverageEnabled: true,
            testingOptions: [],
            testLanguage: nil,
            testRegion: nil,
            testScreenCaptureFormat: nil,
            runLanguage: nil,
            runRegion: nil,
            testPlans: testPlanPathsMock.map { $0.pathString }
        ))
    }
}
