import ProjectDescription
import Foundation

let workspace = Workspace(
    name: "App",
    projects: [
        "./"
    ],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .disabled,
        autogenerateLocalPodsProjects: .automatic(
            [
                "LocalPods/Common/**/*.podspec",
                "LocalPods/Feature/**/*.podspec"
            ]
        )
    )
)
