import Foundation
import struct ProjectDescription.AbsolutePath
import GekoCore
import GekoCoreTesting
import GekoGraph
import XCTest
import GekoSupport

@testable import GekoKit
@testable import GekoSupportTesting

final class GekoWorkspaceRenderMarkdownReadmeMapperTests: GekoUnitTestCase {
    private var subject: GekoWorkspaceRenderMarkdownReadmeMapper!
    private var workspaceDirectory: AbsolutePath!

    override func setUpWithError() throws {
        try super.setUpWithError()
        workspaceDirectory = try temporaryPath()
        subject = .init()
    }

    override func tearDown() {
        subject = nil
        super.tearDown()
    }

    func test_map_with_readme_rendered() throws {
        // Given
        let workspace = Workspace.test(generationOptions: Workspace.GenerationOptions(
            enableAutomaticXcodeSchemes: false,
            autogeneratedWorkspaceSchemes: .disabled,
            lastXcodeUpgradeCheck: nil,
            renderMarkdownReadme: true,
            autogenerateLocalPodsProjects: .disabled,
            autogenerateLocalPodsSchemes: .disabled,
            commonSettings: [],
            configurations: [:])
        )

        let gekoGeneratedFileDescriptor = FileDescriptor(
            path: workspace
                .xcWorkspacePath
                .appending(
                    component: ".xcodesamplecode.plist"
                ),
            contents: try PropertyListEncoder().encode([String]())
        )

        var workspaceWithProjects = WorkspaceWithProjects(workspace: workspace, projects: [])
        // When
        var sideTable = WorkspaceSideTable()
        let sideEffects = try GekoWorkspaceRenderMarkdownReadmeMapper().map(
            workspace: &workspaceWithProjects,
            sideTable: &sideTable
        )

        // Then
        XCTAssertTrue(
            workspaceWithProjects.workspace.generationOptions.renderMarkdownReadme
        )
        XCTAssertTrue(workspaceWithProjects.workspace.projects.isEmpty)
        XCTAssertEqual(
            sideEffects,
            [
                .file(gekoGeneratedFileDescriptor),
            ]
        )
    }

    func test_map_without_readme_rendered() throws {
        // Given
        let workspace = Workspace.test(generationOptions: Workspace.GenerationOptions(
            enableAutomaticXcodeSchemes: false,
            autogeneratedWorkspaceSchemes: .disabled,
            lastXcodeUpgradeCheck: nil,
            renderMarkdownReadme: false,
            autogenerateLocalPodsProjects: .disabled,
            autogenerateLocalPodsSchemes: .disabled,
            commonSettings: [],
            configurations: [:])
        )

        let gekoGeneratedFileDescriptor = FileDescriptor(
            path: workspace
                .xcWorkspacePath
                .appending(
                    component: ".xcodesamplecode.plist"
                ),
            contents: try PropertyListEncoder().encode([String]()),
            state: .absent // file should be deleted
        )
        var workspaceWithProjects = WorkspaceWithProjects(workspace: workspace, projects: [])
        // When
        var sideTable = WorkspaceSideTable()
        let sideEffects = try GekoWorkspaceRenderMarkdownReadmeMapper().map(
            workspace: &workspaceWithProjects,
            sideTable: &sideTable
        )

        // Then
        XCTAssertFalse(
            workspaceWithProjects.workspace.generationOptions.renderMarkdownReadme
        )
        XCTAssertTrue(workspaceWithProjects.workspace.projects.isEmpty)
        XCTAssertEqual(
            sideEffects,
            [
                .file(gekoGeneratedFileDescriptor),
            ]
        )
    }
}
