import Foundation
import ProjectDescription
@testable import GekoGraph

extension Workspace {
    public static func test(
        path: AbsolutePath = try! AbsolutePath(validatingAbsolutePath: "/"), // swiftlint:disable:this force_try
        xcWorkspacePath: AbsolutePath = try! AbsolutePath(validatingAbsolutePath: "/"), // swiftlint:disable:this force_try
        name: String = "test",
        projects: [AbsolutePath] = [],
        schemes: [Scheme] = [],
        ideTemplateMacros: IDETemplateMacros? = nil,
        additionalFiles: [FileElement] = [],
        generationOptions: GenerationOptions = .test()
    ) -> Workspace {
        Workspace(
            path: path,
            xcWorkspacePath: xcWorkspacePath,
            name: name,
            projects: projects,
            schemes: schemes,
            generationOptions: generationOptions,
            ideTemplateMacros: ideTemplateMacros,
            additionalFiles: additionalFiles
        )
    }
}

extension Workspace.GenerationOptions {
    public static func test(
        enableAutomaticXcodeSchemes: Bool? = false,
        autogeneratedWorkspaceSchemes: AutogeneratedWorkspaceSchemes = .enabled(
            codeCoverageMode: .disabled,
            testingOptions: [],
            testLanguage: nil,
            testRegion: nil,
            testScreenCaptureFormat: nil
        ),
        lastXcodeUpgradeCheck: Version? = nil,
        commonSettings: [CommonSettings] = [],
        configurations: [String: BuildConfiguration.Variant] = ["Debug": .debug, "Release": .release]
    ) -> Self {
        .init(
            enableAutomaticXcodeSchemes: enableAutomaticXcodeSchemes,
            autogeneratedWorkspaceSchemes: autogeneratedWorkspaceSchemes,
            lastXcodeUpgradeCheck: lastXcodeUpgradeCheck,
            renderMarkdownReadme: false,
            autogenerateLocalPodsProjects: .disabled,
            autogenerateLocalPodsSchemes: .disabled,
            commonSettings: commonSettings,
            configurations: configurations
        )
    }
}
