import Foundation
import ProjectDescription
import GekoCoreTesting
import GekoGraph
import GekoLoader
import XCTest
import GekoCache
@testable import GekoAutomation
@testable import GekoCore
@testable import GekoGenerator
@testable import GekoKit
@testable import GekoSupportTesting

final class WorkspaceMapperFactoryTests: GekoUnitTestCase {
    var projectMapperFactory: ProjectMapperFactory!
    var subject: WorkspaceMapperFactory!

    override func setUp() {
        super.setUp()
        projectMapperFactory = ProjectMapperFactory()
    }

    override func tearDown() {
        projectMapperFactory = nil
        subject = nil
        super.tearDown()
    }

    func test_default_contains_the_replace_local_references_mapper() {
        // Given
        subject = WorkspaceMapperFactory(projectMapper: SequentialProjectMapper(mappers: projectMapperFactory.default()))
        let config = Config.test()

        // When
        let got = subject.default(config: config)

        // Then
        XCTAssertContainsElementOfType(got, ReplaceLocalReferencesWorkspaceMapper.self)
    }

    func test_default_contains_the_configurations_mapper() {
        // Given
        subject = WorkspaceMapperFactory(projectMapper: SequentialProjectMapper(mappers: projectMapperFactory.default()))
        let config = Config.test()

        // When
        let got = subject.default(config: config)

        // Then
        XCTAssertContainsElementOfType(got, ConfigurationsWorkspaceMapper.self)
    }

    func test_default_contains_the_common_settings_mapper() {
        // Given
        subject = WorkspaceMapperFactory(projectMapper: SequentialProjectMapper(mappers: projectMapperFactory.default()))
        let config = Config.test()

        // When
        let got = subject.default(config: config)

        // Then
        XCTAssertContainsElementOfType(got, CommonSettingsMapper.self)
    }

    func test_default_contains_resource_bundle_sign_mapper() {
        // Given
        subject = WorkspaceMapperFactory(projectMapper: SequentialProjectMapper(mappers: projectMapperFactory.default()))
        let config = Config.test()

        // When
        let got = subject.default(config: config)

        // Then
        XCTAssertContainsElementOfType(got, CommonSettingsMapper.self)
    }

    func test_default_contains_the_project_workspace_mapper() {
        // Given
        subject = WorkspaceMapperFactory(projectMapper: SequentialProjectMapper(mappers: projectMapperFactory.default()))
        let config = Config.test()

        // When
        let got = subject.default(config: config)

        // Then
        XCTAssertContainsElementOfType(got, ProjectWorkspaceMapper.self)
    }

    func test_default_contains_the_geko_workspace_identifier_mapper() {
        // Given
        subject = WorkspaceMapperFactory(projectMapper: SequentialProjectMapper(mappers: projectMapperFactory.default()))
        let config = Config.test()

        // When
        let got = subject.default(config: config)

        // Then
        XCTAssertContainsElementOfType(got, GekoWorkspaceIdentifierMapper.self)
    }

    func test_default_contains_the_geko_workspace_render_markdown_readme_mapper() {
        // Given
        subject = WorkspaceMapperFactory(projectMapper: SequentialProjectMapper(mappers: projectMapperFactory.default()))
        let config = Config.test()

        // When
        let got = subject.default(config: config)

        // Then
        XCTAssertContainsElementOfType(got, GekoWorkspaceRenderMarkdownReadmeMapper.self)
    }

    func test_default_contains_the_tide_template_macros_mapper() {
        // Given
        subject = WorkspaceMapperFactory(projectMapper: SequentialProjectMapper(mappers: projectMapperFactory.default()))
        let config = Config.test()

        // When
        let got = subject.default(config: config)

        // Then
        XCTAssertContainsElementOfType(got, IDETemplateMacrosMapper.self)
    }

    func test_default_contains_the_autogenerated_project_scheme_mapper_when_autogenerated_schemes_are_enabled() {
        // Given
        subject = WorkspaceMapperFactory(projectMapper: SequentialProjectMapper(mappers: projectMapperFactory.default()))
        let config = Config.test()

        // When
        let got = subject.default(config: config)

        // Then
        XCTAssertContainsElementOfType(got, AutogeneratedWorkspaceSchemeWorkspaceMapper.self)
    }

    func test_default_contains_the_last_upgrade_version_mapper() {
        // Given
        subject = WorkspaceMapperFactory(projectMapper: SequentialProjectMapper(mappers: projectMapperFactory.default()))
        let config = Config.test()

        // When
        let got = subject.default(config: config)

        // Then
        XCTAssertContainsElementOfType(got, LastUpgradeVersionWorkspaceMapper.self)
    }

    func test_cache_contains_the_generate_cache_project_mapper() {
        // Given
        subject = WorkspaceMapperFactory(projectMapper: SequentialProjectMapper(mappers: projectMapperFactory.default()))
        let config = Config.test()
        let profile = Cache.Profile.test()

        // When
        let got = subject.cache(config: config, cacheProfile: profile)

        // Then
        XCTAssertContainsElementOfType(got, GenerateCacheProjectMapper.self)
    }

    func test_default_contains_the_plugin_executor_mapper() {
        // Given
        subject = WorkspaceMapperFactory(projectMapper: SequentialProjectMapper(mappers: projectMapperFactory.default()))
        let config = Config.test()

        // When
        let got = subject.default(config: config)

        // Then
        XCTAssertContainsElementOfType(got, WorkspaceMapperPluginExecutor.self, after: DeleteDerivedDirectoryWorkspaceMapper.self)
    }
}
