@preconcurrency import ProjectDescription
import Foundation

let workspace = Workspace(
    name: "App",
    projects: [
        "./"
    ],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .disabled,
        autogenerateLocalPodsProjects: .automatic(
            [
                "LocalPods/Common/**/*.podspec",
                "LocalPods/Feature/**/*.podspec"
            ]
        ),
        commonSettings: [["IPHONEOS_DEPLOYMENT_TARGET": "15.0"]]
    )
)
