import Foundation
import GekoAutomation
import GekoCore
import GekoGenerator
import GekoGraph
import GekoLoader
import GekoSupport

/// The protocol describes an interface for getting project mappers.
protocol ProjectMapperFactorying {
    /// Returns the default project mapper.
    /// - Parameter config: The project configuration
    /// - Returns: A project mapper instance.
    func `default`() -> [ProjectMapping]

    /// Returns a project mapper for automation.
    /// - Parameter config: The project configuration.
    /// - Parameter skipUITests: Whether UI tests should be skipped.
    /// - Returns: An instance of a project mapper.
    func automation(skipUITests: Bool) -> [ProjectMapping]

    /// Returns a project mappers for cache
    /// - Parameter cacheProfile: Cache profile model
    /// - Returns: Array of project mappers
    func cache(cacheProfile: GekoGraph.Cache.Profile) -> [ProjectMapping]
}

public final class ProjectMapperFactory: ProjectMapperFactorying {
    private let contentHasher: ContentHashing

    public init(contentHasher: ContentHashing = ContentHasher()) {
        self.contentHasher = contentHasher
    }

    public func automation(skipUITests: Bool) -> [ProjectMapping] {
        var mappers: [ProjectMapping] = []
        mappers += self.default()

        mappers.append(
            SourceRootPathProjectMapper()
        )

        if skipUITests {
            mappers.append(
                SkipUITestsProjectMapper()
            )
        }

        return mappers
    }

    func cache(cacheProfile: GekoGraph.Cache.Profile) -> [ProjectMapping] {
        var mappers: [ProjectMapping] = [
            ResourceBundleActiveResourcesProjectMapper(
                onlyActiveResources: cacheProfile.options.onlyActiveResourcesInBundles
            ),
            ExportCoverageProfilesProjectMapper(
                exportCoverageProfiles: cacheProfile.options.exportCoverageProfiles
            ),
        ]
        mappers.append(contentsOf: self.default())
        return mappers
    }

    public func `default`() -> [ProjectMapping] {
        var mappers: [ProjectMapping] = []

        mappers.append(GenerateDummySourceFileProjectMapper())

        mappers.append(CreateDraftFilesProjectMapper())

        mappers.append(CocoapodsModuleMapProjectMapper())

        // Logfile noise suppression
        mappers.append(TargetActionDisableShowEnvVarsProjectMapper())

        // Support for resources in libraries
        mappers.append(ResourcesProjectMapper(contentHasher: ContentHasher()))

        // Auto-generation of schemes
        // This mapper should follow the ResourcesProjectMapper in order to create schemes for bundles and cache them.
        mappers.append(AutogeneratedSchemesProjectMapper())

        // Info Plist
        mappers.append(GenerateInfoPlistProjectMapper())

        // Entitlements
        mappers.append(GenerateEntitlementsProjectMapper())

        // Template macros
        mappers.append(IDETemplateMacrosMapper())

        mappers.append(SourceRootPathProjectMapper())

        return mappers
    }
}
