import Foundation
import GekoCache
import ProjectDescription
import GekoAutomation
import GekoCore
import GekoGenerator
import GekoGraph
import GekoDependencies

protocol WorkspaceMapperFactorying {
    /// Returns the default workspace mapper.
    /// - Returns: A workspace mapping instance.
    func `default`(config: Config) -> [WorkspaceMapping]

    /// Returns a mapper to generate cacheable prorjects.
    /// - Parameter config: The project configuration.
    /// - Parameter cacheProfile: The caching profile.
    /// - Returns: A workspace mapping instance.
    func cache(config: Config, cacheProfile: GekoGraph.Cache.Profile) -> [WorkspaceMapping]

    /// Returns a mapper for automation commands like build and test.
    /// - Parameter config: The project configuration.
    /// - Returns: A workspace mapping instance.
    func automation(config: Config) -> [WorkspaceMapping]
}

public final class WorkspaceMapperFactory: WorkspaceMapperFactorying {
    private let projectMapper: ProjectMapping

    public init(
        projectMapper: ProjectMapping
    ) {
        self.projectMapper = projectMapper
    }

    func automation(config: Config) -> [WorkspaceMapping] {
        var mappers: [WorkspaceMapping] = []
        mappers += self.default(config: config, forceWorkspaceSchemes: true)

        return mappers
    }

    func cache(config: Config, cacheProfile: GekoGraph.Cache.Profile) -> [WorkspaceMapping] {
        var mappers: [WorkspaceMapping] = [GenerateCacheProjectMapper(cacheProfile: cacheProfile)]
        mappers.append(contentsOf: self.default(config: config))
        return mappers
    }

    func `default`(config: Config) -> [WorkspaceMapping] {
        self.default(config: config, forceWorkspaceSchemes: false)
    }

    public func `default`(config: Config, forceWorkspaceSchemes: Bool) -> [WorkspaceMapping] {
        var mappers: [WorkspaceMapping] = []

        mappers.append(
            ReplaceLocalReferencesWorkspaceMapper()
        )

        mappers.append(
            DeleteDerivedDirectoryWorkspaceMapper()
        )

        mappers.append(
            ResolvePathsWorkspaceMapper()
        )

        mappers.append(
            WorkspaceMapperPluginExecutor(stage: .rawGlobs)
        )

        mappers.append(
            ResolveGlobsWorkspaceMapper(checkFilesExist: true)
        )

        mappers.append(
            WorkspaceMapperPluginExecutor(stage: .resolvedGlobs)
        )

        mappers.append(
            ResolveTargetRulesWorkspaceMapper()
        )

        mappers.append(
            ConfigurationsWorkspaceMapper()
        )

        mappers.append(
            ProjectWorkspaceMapper(mapper: projectMapper)
        )

        mappers.append(
            GekoWorkspaceIdentifierMapper()
        )

        mappers.append(
            GekoWorkspaceRenderMarkdownReadmeMapper()
        )

        mappers.append(
            IDETemplateMacrosMapper()
        )

        mappers.append(
            AutogeneratedWorkspaceSchemeWorkspaceMapper(forceWorkspaceSchemes: forceWorkspaceSchemes)
        )

        mappers.append(
            CommonSettingsMapper()
        )

        mappers.append(
            ResourceBundleSignMapper()
        )

        mappers.append(
            LastUpgradeVersionWorkspaceMapper()
        )

        mappers.append(
            WorkspaceRootMapper()
        )

        mappers.append(
            SPMDependencyPathWorkspaceMapper()
        )

        return mappers
    }
}
